---
title: "R Notebook"
output: html_notebook
---

Weather Forecast Homework

#Question 1

```{r}
weather_forcast <- list(
                  "Thursday" = list(temperature = 8, chance_of_rain = 14, wind_speed = 21),
                  "Friday" = list(temperature = 11, chance_of_rain = 30, wind_speed = 44),
                  "Saturday" = list(temperature = 11, chance_of_rain = 10, wind_speed = 16)
)
```

# Question 2

```{r}
day <- c('Thursday', 'Friday', 'Saturday')
temperature <- c(8, 11, 11)
chance_of_rain <- c(14, 30, 10)
wind_speed <- c(21, 44, 16)
weather_forcast <- tibble (temperature, chance_of_rain, wind_speed)
tibble(temperature, chance_of_rain, wind_speed) %>% 

```

i) 14
ii) 44
iii) 8

# Question 3

```{r} 
weather_fortnight <- matrix(c(9, 11, 11, 10, 11, 11, 10, 10, 11, 11, 11, 11, 11, 10), nrow = 2, ncol = 7)

weather_fortnight
```

#Question 4
```{r}
weather_fortnight [2,3]
weather_fortnight [2, ]
weather_fortnight [, c(1, 3, 5)]
```

# Answers

# Question 5

```{r}
answer_or_divide <- function(x) {
  if (is.character(x)) {
    return(paste("The answer is: ", x))
  }

  if (is.numeric(x)) {
    if (x < 10) {
      return(x)
    } else {
      return(x / 10)
    }
  }

  return("Invalid input")
}
```

```{r}
char_test <- "12"
less_than_10_test <- 9
greater_than_10_test <- 12
test_10 <- 10
```

```{r}
place_holder <- test_10

find_answer <- function(place_holder) {
  if (is.character(place_holder)) {
  result <- paste0("The answer is: ", place_holder)
} else if (place_holder < 10) {
  result <- place_holder
} else if (place_holder > 10) {
  result <- place_holder / 10
} else {
  result <- "Invalid input"
}
  print(result)
}

find_answer(char_test)
find_answer(greater_than_10_test)
find_answer(less_than_10_test)
find_answer(test_10)

```
# Question 6

```{r}
test_1 <- 1:3
test_2 <- 3:1
test_3 <- 4:6
test_4 <- c(1, 3, 4)

x = test_1
y = test_3

check_sameness <- function(x, y)

if (all(x == y) {
  return("met")
} else if(all(sort(x) == sort(y))) {
  return("almost met")
} else {
  return("not even close")
}

check_sameness(test_1, test_1)
check_sameness(test_1, test_2)
check_sameness(test_1, test_3)

```

