---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
movies <- read_csv("../day_3/data/movies.csv")
```

```{r}
movies_selected <- movies %>% 
  select(title, budget, runtime)
```

```{r}
movies_selected %>% 
  summarise(na_title = sum(is.na(title)),
            na_budget = sum(is.na(budget)),
             na_runtime = sum(is.na(runtime)))
```

```{r}
movies_runtime <- movies_selected %>% 
  mutate(runtime = na_if(runtime, 0)) 
```

```{r}
movies_runtime %>% 
  summarise(count = sum(is.na(runtime)))
```

```{r}
movies_imputed <- movies_runtime %>% 
  mutate(runtime = coalesce(runtime, median(runtime, na.rm = TRUE)))
```

```{r}
movies_imputed %>% 
  summarise(count = sum(is.na(runtime)))
```

```{r}
movies_imputed %>% 
  slice_max(runtime, n= 10)
```

```{r}
movies_imputed %>% 
  slice_min(runtime, n = 10)
```

```{r}
movies_imputed <- movies_imputed %>% 
  mutate(budget = if_else(budget <100, median(budget), budget))
```

```{r}
movies_imputed %>% 
  mutate(budget_type = case_when(
    budget < 12000000 ~ "Small budget",
    budget < 40000000 ~ "Medium budget",
    .default = "Big budget"
  ))
```

