---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(CodeClanData)
library(janitor)
```

```{r}
meteorite_landings <- read_csv("data/meteorite_landings.csv")
```

```{r}
meteorite_landings %>% 
  dim()
```
```{r}
meteorite_landings %>% 
  glimpse()
```


Question 2

```{r}
meteorite_landings <- meteorite_landings %>% 
  clean_names()
```

# Question 3

```{r}
meteorite_landings_geo <- meteorite_landings %>% 
  separate(geo_location, c("latitude", "longitude"), sep = "\\,")

meteorite_landings_geo
#need to find out how to get rid of brackets
```

# Question 4 - Need to work on

```{r}
meteorite_landings_geo %>% 
  mutate(latitude, is.na = 0)
```

Question 4 - Mark 2

# Found this code from the internet

```{r}
meteorite_landings_geo %>% 
  mutate_if(is.numeric, longitude, ~replace(., is.na(.), 0))
```


# Question 5 

Filtering out light meteorites of below 1000g

```{r}
heavy_meteorite_landing <- meteorite_landings_geo %>% 
  filter(mass_g > 1000)
```

```{r}
meteorite_landing_year <- heavy_meteorite_landing %>% 
  arrange(year)
```

Part 2 - The RMD file

# Question 2

```{r}
meteorite_landings %>% 
  select(name, mass_g, year) %>% 
  arrange(desc(mass_g)) %>% 
  head(10)

```

# Question 3

```{r}
meteorite_landings %>% 
  group_by(fall) %>% 
  summarise(mean_mass_g = mean(mass_g))
  
```

